# Development Services
services:
    app:
        # don't start app container per default
        profiles: [app]
        depends_on:
            - authelia
            - db
        build:
            context: .
            dockerfile: docker/Dockerfile
        restart: unless-stopped
        ports:
            - "8080:80"
        env_file: .env
    db:
        image: docker.io/postgres:18
        restart: unless-stopped
        volumes:
            - db:/var/lib/postgresql
        ports:
            - "${DFM_DB_PORT}:5432"
        environment:
            - POSTGRES_USER=${DFM_DB_USER}
            - POSTGRES_PASSWORD=${DFM_DB_PASSWORD}
            - POSTGRES_DB=${DFM_DB_NAME}
    authelia:
        image: docker.io/authelia/authelia:4.39.16
        restart: unless-stopped
        ports:
            - "9091:9091"
        networks:
            default:
                aliases:
                    - authelia.localhost
        volumes:
            - ./docker/authelia-config:/config:ro
            - authelia-secrets:/secrets

volumes:
    db:
    authelia-secrets:
