import * as oidc from 'openid-client';
import type {
    Request as ExpressRequest,
    Response as ExpressResponse,
} from 'express';
import { toFrontend } from '../utils/frontend-http-helper.js';
import { Config } from '../config.js';
import type { AuthService } from './auth-service.js';

export namespace OidcService {
    export interface UserInfo {
        id: string;
        displayName: string;
        username: string;
    }
}

export class OidcService {
    // this is the length of the randomState generated by oidc.randomState()
    // https://github.com/panva/oauth4webapi/blob/31767a69e69929b0180e7e243415577533b01d54/src/index.ts#L1482-L1484
    public readonly OIDC_RANDOM_STATE_LENGTH = 43;

    private _config: oidc.Configuration | null = null;
    private _publicUrl: string = Config.httpBackendUrl;
    private static readonly redirectPath = '/api/auth/oidc-callback';

    public constructor(private readonly authService: AuthService) {}

    public get config(): oidc.Configuration {
        if (this._config === null) {
            throw new Error('AuthService not initialized');
        }
        return this._config;
    }

    public async initialize(opts?: { skipOidcDiscovery?: boolean }) {
        try {
            Config.initialize();
            if (!(opts?.skipOidcDiscovery ?? false)) {
                this._config = await oidc.discovery(
                    new URL(Config.authUrl),
                    Config.authClientId,
                    Config.authClientSecret,
                    undefined,
                    {
                        execute:
                            process.env['NODE_ENV'] === 'development'
                                ? [
                                      /*
                                       * Marked as deprecated only to make it stand out as something you shouldn't
                                       * have the need to use, possibly only for local development and testing
                                       * against non-TLS secured environments.
                                       * https://github.com/panva/openid-client/blob/01f5fe37cbe78c8c2624f0e568fc3a7d4d2386eb/docs/functions/allowInsecureRequests.md
                                       */
                                      oidc.allowInsecureRequests,
                                  ]
                                : undefined,
                    }
                );
            }
            this._publicUrl = Config.httpBackendUrl;
            return this;
        } catch (err) {
            console.log('OidcService initialisation failed');
            throw err;
        }
    }

    public async getAuthUrl(opts?: {
        returnTo?: string;
        urlTransformer: (url: URL) => URL;
    }): Promise<{
        url: URL;
        cookies: { name: string; value: string }[];
    }> {
        // see https://github.com/panva/openid-client/blob/01f5fe37cbe78c8c2624f0e568fc3a7d4d2386eb/README.md
        const codeVerifier = oidc.randomPKCECodeVerifier();
        const codeChallenge =
            await oidc.calculatePKCECodeChallenge(codeVerifier);
        const state =
            oidc
                .randomState()
                .slice(0, this.OIDC_RANDOM_STATE_LENGTH)
                .padEnd(this.OIDC_RANDOM_STATE_LENGTH, '=') +
            (opts?.returnTo ?? '');

        const parameters: { [key: string]: string } = {
            redirect_uri: this._publicUrl + OidcService.redirectPath,
            scope: 'openid profile email',
            code_challenge: codeChallenge,
            code_challenge_method: 'S256',
            state,
        };

        const cookies = [
            { name: 'code-verifier', value: codeVerifier },
            { name: 'state', value: state },
        ];

        let authUrl = oidc.buildAuthorizationUrl(this.config, parameters);
        if (opts?.urlTransformer) {
            authUrl = opts.urlTransformer(authUrl);
        }

        return {
            url: authUrl,
            cookies,
        };
    }

    public get userSelfServiceEnabled(): boolean {
        return Config.authSelfServiceUrl !== '';
    }

    public get userRegistrationEnabled(): boolean {
        return Config.authUserRegistrationAdapter !== '';
    }

    public async handleRegistrationRedirect(
        req: ExpressRequest,
        res: ExpressResponse
    ) {
        switch (Config.authUserRegistrationAdapter) {
            case 'keycloak':
                this.handleLoginRedirect(req, res, (url) => {
                    url.pathname = url.pathname.replace(
                        'openid-connect/auth',
                        'openid-connect/registrations'
                    );
                    return url;
                });
                break;
            default:
                res.redirect(
                    toFrontend(undefined, {
                        loginFailure: 'Registrierung nicht verfügbar',
                    })
                );
        }
    }

    public async handleLoginRedirect(
        req: ExpressRequest,
        res: ExpressResponse,
        urlTransformer: (url: URL) => URL = (url) => url
    ) {
        const returnToPath = req.query['returnto'] as string | undefined;
        const authUrl = await this.getAuthUrl({
            returnTo: returnToPath,
            urlTransformer,
        });

        for (const cookie of authUrl.cookies) {
            res.cookie(cookie.name, cookie.value, {
                httpOnly: true,
                path: '/api/auth/oidc-callback',
                sameSite: 'lax',
            });
        }

        res.redirect(authUrl.url.toString());
    }

    public async handleCallback(req: ExpressRequest, res: ExpressResponse) {
        const state = req.cookies['state'] as string | undefined;
        const codeVerifier = req.cookies['code-verifier'];

        if (state === undefined || codeVerifier === undefined) {
            res.redirect(
                toFrontend(undefined, {
                    loginFailure: 'Unvollständige Anmeldung',
                })
            );
            return;
        }

        const fullUrl = new URL(`${this._publicUrl}${req.originalUrl}`);

        const tokens = await oidc.authorizationCodeGrant(this.config, fullUrl, {
            expectedState: state,
            pkceCodeVerifier: codeVerifier,
        });
        res.clearCookie('code-verifier');
        res.clearCookie('state');

        const userInfo = await this.fetchUserInfo(tokens.access_token);

        const sessionToken = await this.authService.createNewSession({
            user: userInfo,
            accessToken: tokens.access_token,
        });

        const returnTo =
            state.length > this.OIDC_RANDOM_STATE_LENGTH
                ? state.slice(this.OIDC_RANDOM_STATE_LENGTH)
                : undefined;

        res.cookie(this.authService.SESSION_COOKIE_NAME, sessionToken, {
            httpOnly: true,
        }).redirect(toFrontend(returnTo, { loginSuccess: true }));
    }

    public async handleSelfServiceRedirect(
        req: ExpressRequest,
        res: ExpressResponse
    ) {
        if (!this.userSelfServiceEnabled) {
            res.redirect(
                toFrontend(undefined, {
                    loginFailure: 'Benutzer-Selbstverwaltung nicht verfügbar',
                })
            );
            return;
        }

        const selfServiceUrl = new URL(Config.authSelfServiceUrl);

        res.redirect(selfServiceUrl.toString());
    }

    public async fetchUserInfo(
        accessToken: string
    ): Promise<OidcService.UserInfo> {
        const userInfo = await oidc.fetchUserInfo(
            this.config,
            accessToken,
            // we dont have a stored sub to verify against, so we skip this
            oidc.skipSubjectCheck
        );

        const username = userInfo.preferred_username ?? userInfo.email ?? null;
        const displayName = userInfo.name ?? username ?? null;

        return {
            id: userInfo.sub,
            displayName: displayName ?? 'NONAME',
            username: username ?? 'NOUSERNAME',
        };
    }

    public async getSingleSignOutUrl() {
        if (!this.config.serverMetadata().frontchannel_logout_supported) {
            return null;
        }
        return oidc.buildEndSessionUrl(this.config, {
            post_logout_redirect_uri: toFrontend(undefined, {
                logoutStatus: 'loggedOut',
            }),
        });
    }
}
